[package]
name = "my_site"
version = "0.1.0"
authors = ["James Lennon"]
edition = "2021"

[dependencies]
egui = "0.30"
eframe = { version = "0.30", default-features = false, features = [
    "default_fonts", # Embed the default egui fonts.
    "glow",          # Use the glow rendering backend. Alternative: "wgpu".
] }
egui_extras = { version = "*", features = ["default", "all_loaders", "image"] }
image = { version = "0.25", features = ["png"] }
log = "0.4"

# native:
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
env_logger = "0.11"

# web:
# Note: The web crates cannot be updated until egui is updated
# past 0.28.1 due to a breaking change in the wasm-bindgen crate.
#[target.'cfg(target_arch = "wasm32")'.dependencies]
#wasm-bindgen-futures = "=0.4.42"
#wasm-bindgen = "=0.2.92"
#web-sys = "=0.3.69"

[profile.release]
opt-level = 2   # fast and small wasm
panic = "abort"

# Optimize all dependencies even in debug builds:
[profile.dev.package."*"]
opt-level = 3
